name: Hourly Data Refresh

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  refresh_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: energy_forecasting/Dockerfile
          push: false
          load: true
          tags: energy-forecasting:latest

      - name: Run data refresh script in container
        run: |
          docker run --rm \
            -e EIA_API_KEY=${{ secrets.EIA_API_KEY }} \
            energy-forecasting:latest \
            python /app/src/data_refresh.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated data refresh" && git push)
