name: Hourly Data Refresh

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

env:
  EIA_API_KEY: ${{ secrets.EIA_API_KEY }}

jobs:
  refresh_data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: energy_forecasting/Dockerfile
          push: false
          load: true
          tags: energy-forecasting:latest

      - name: Create data directory
        run: mkdir -p ${{ github.workspace }}/data

      - name: Run Docker container (data refresh)
        run: |
          docker run --rm \
            -e EIA_API_KEY=${{ secrets.EIA_API_KEY }} \
            -v ${{ github.workspace }}/data:/app/data \
            energy-forecasting:latest

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Update data" || exit 0
          git push
