name: Hourly Data Refresh

on:
  schedule:
    - cron: "* */1 * * *"
  workflow_dispatch:

jobs:
  refresh_data:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: energy_forecasting/Dockerfile
          push: false
          tags: energy-forecasting:latest

      - name: Run data refresh script in container
        uses: docker/containers-action@v1
        with:
          image: energy-forecasting:latest
          run: python /app/src/data_refresh.py
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated data refresh" && git push)
