name: Daily Data Refresh

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # This allows manual triggering

jobs:
  refresh_data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: false
          load: true
          tags: energy-forecasting:latest

      - name: Create directories
        run: |
          mkdir -p ${{ github.workspace }}/data
          mkdir -p ${{ github.workspace }}/docs
          mkdir -p ${{ github.workspace }}/mlruns/models
          mkdir -p ${{ github.workspace }}/mlartifacts/351954414414469151

      - name: Run Docker container
        run: |
          docker run --rm \
            -e EIA_API_KEY=${{ secrets.EIA_API_KEY }} \
            -e DATA_PATH=${{ secrets.DATA_PATH }} \
            -e MODELS_PATH=${{ secrets.MODELS_PATH }} \
            -e HOME_PATH=${{ secrets.HOME_PATH }} \
            -v ${{ github.workspace }}/data:/app/data \
            -v ${{ github.workspace }}/docs:/app/docs \
            -v ${{ github.workspace }}/mlruns/models:/app/mlruns/models \
            -v ${{ github.workspace }}/mlartifacts/351954414414469151:/app/mlartifacts/351954414414469151 \
            energy-forecasting:latest \
            bash /app/run_scripts.sh
      - name: Commit and pull/push if it changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git pull
          git push
