name: Daily Data Refresh

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # This allows manual triggering

env:
  DATA_PATH: ${{ secrets.DATA_PATH }}
  EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
  MODELS_PATH: ${{ secrets.MODELS_PATH }}

jobs:
  refresh_data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: false
          load: true
          tags: energy-forecasting:latest

      - name: Create data directory
        run: mkdir -p ${{ github.workspace }}/data

      - name: Run Docker container
        run: |
          docker run --rm \
            -e EIA_API_KEY=${{ secrets.EIA_API_KEY }} \
            -e DATA_PATH=${{ secrets.DATA_PATH }} \
            -e MODELS_PATH=${{ secrets.MODELS_PATH }} \
            -v ${{ github.workspace }}/data:/app/data \
            energy-forecasting:latest \
            bash /app/run_scripts.sh
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git pull
          git push
